### PR TITLE
Update Gromix-MPX runtime to 46 and more

### LINKED ISSUE #210: Flatpak does not show cross cursor when built with runtime 46
re https://github.com/flathub/net.christianbeier.Gromit-MPX/pull/10

### PR DESCRIPTION
**Pull request by ghost**
- Update Gromix-MPX runtime to 46
- Update gnome-settings-daemon version to 46.0
- Change flatpak finish-args to fix https://github.com/bk138/gromit-mpx/issues/210
- Remove some redundant files to reduce package size (share/doc,share/man, share/vala)

### CODE REVIEW

**Comment by ghost** [comment]
@bk138 Could you test again.

**Comment by bk138** [comment]
@yakushabb the additional changes seem unrelated to https://github.com/bk138/gromit-mpx/issues/210 - what did your tests yield?

**Comment by ghost** [comment]
> @yakushabb the additional changes seem unrelated to [bk138/gromit-mpx#210](https://github.com/bk138/gromit-mpx/issues/210) - what did your tests yield?

The following changes are experimental and related to cursor error.

I've separated cleanup changes into another commit.

```
  # ? share IPC namespace with the host
  # ? This is not necessarily required, but without it the X11 shared memory extension
  # will not work, which is very bad for X11 performance.
  - --share=ipc
  #  ? show windows using X11,
  # if Wayland is not available, overrides x11 socket permission.
  # Note that you must still use --socket=wayland for wayland permission
  - --socket=fallback-x11
  #  ? Show windows with Wayland
  - --socket=wayland
  #  ? Direct Rendering Interface. Necessary for GL.
  - --device=dri
```

**Comment by ghost** [comment]
> what did your tests yield?

I couldn't replicate the issue (https://github.com/bk138/gromit-mpx/issues/210) could you test again?

Thanks.

**Comment by bk138** [comment]
> Build [133110 successful](https://buildbot.flathub.org/#/builders/6/builds/133110) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/116111/net.christianbeier.Gromit-MPX.flatpakref
> ```

This does not even start for me under Wayland: `(gromit-mpx:2): Gtk-WARNING **: 15:31:04.213: cannot open display:"`

@yakushabb please don't change the flatpak flags, it's got nothing to do with this. The reason is a change in gdk-pixbuf.

**Comment by bk138** [comment]
Closing this, let's track progress on this in the main repo at https://github.com/bk138/gromit-mpx/issues/210

**Pull request closed without merging**
